/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dean;
import Model.Faculty;
import Service.Deanservise;
import Service.FacultyServise;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M NJERIC
 */
public class DeanForm extends javax.swing.JFrame {

    /**
     * Creates new form DeanForm
     */
    public DeanForm() {
        initComponents();
         displaydata();
    }
    private void displaydata(){
        
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
           Deanservise facs=(Deanservise) reg.lookup("Deancall");
           List<Dean> thedean=facs.deandata();
            DefaultTableModel tmodel=(DefaultTableModel)Deantabledata.getModel();
            tmodel.setRowCount(0);
           if(thedean!=null){
               for(Dean deans:thedean){
                   Object data[]={
                       
                       deans.getDeanId(),
                       deans.getName()
                   };
                   tmodel.addRow(data);
                  
               }
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegisterDeanBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Deanname = new javax.swing.JTextField();
        UpdateDeanBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Deanid = new javax.swing.JTextField();
        SearchDeanBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Deantabledata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Dean Registration Form");

        RegisterDeanBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RegisterDeanBTN.setText("Register");
        RegisterDeanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDeanBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel2.setText("Full Names :");

        Deanname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Deanname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeannameActionPerformed(evt);
            }
        });

        UpdateDeanBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UpdateDeanBTN.setText("Update");
        UpdateDeanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeanBTNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel3.setText("Dean ID :");

        Deanid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Deanid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeanidActionPerformed(evt);
            }
        });

        SearchDeanBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SearchDeanBTN.setText("Search");
        SearchDeanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDeanBTNActionPerformed(evt);
            }
        });

        Deantabledata.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Deantabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dean ID ", "Dean Name"
            }
        ));
        Deantabledata.setRowHeight(40);
        jScrollPane1.setViewportView(Deantabledata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Deanid, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(SearchDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(382, 382, 382)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Deanname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(RegisterDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(UpdateDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deanname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Deanid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchDeanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeannameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeannameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeannameActionPerformed

    private void DeanidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeanidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeanidActionPerformed

    private void RegisterDeanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDeanBTNActionPerformed
      ///Validation
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            Deanservise deans=(Deanservise) reg.lookup("Deancall");
            Dean dm=new Dean();
            dm.setName(Deanname.getText());
            Dean thedean=deans.Registerdn(dm);
            
            if(thedean!=null){
                JOptionPane.showMessageDialog(this, "Data Saved Successful");
            }else{
                 JOptionPane.showMessageDialog(this, "Data not Saved");
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_RegisterDeanBTNActionPerformed

    private void SearchDeanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDeanBTNActionPerformed
        try{
        Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
           Deanservise facs=(Deanservise) reg.lookup("Deancall");
          Dean thedean=new Dean();
          thedean.setDeanId(Integer.parseInt(Deanid.getText()));
           Dean deanobj=facs.searchingdn(thedean);
           if(deanobj!=null){
               Deanname.setText(deanobj.getName());
           }else{
               JOptionPane.showMessageDialog(this,"Dean ID not Exist! Register Now");
        }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchDeanBTNActionPerformed

    private void UpdateDeanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeanBTNActionPerformed
         try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            Deanservise deans=(Deanservise) reg.lookup("Deancall");
            Dean dm=new Dean();
            dm.setName(Deanname.getText());
            dm.setDeanId( Integer.parseInt(Deanid.getText()));
            Dean thedean=deans.updatedn(dm);
            
            if(thedean!=null){
                JOptionPane.showMessageDialog(this, "Data Updated Successful");
                Deanname.setText("");
                 displaydata();
            }else{
                 JOptionPane.showMessageDialog(this, "Data not Updated");
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateDeanBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Deanid;
    private javax.swing.JTextField Deanname;
    private javax.swing.JTable Deantabledata;
    private javax.swing.JButton RegisterDeanBTN;
    private javax.swing.JButton SearchDeanBTN;
    private javax.swing.JButton UpdateDeanBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
