/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dean;
import Model.Faculty;
import Service.Deanservise;
import Service.FacultyServise;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javafx.scene.control.ComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author M NJERIC
 */
public class FacultyForm extends javax.swing.JFrame {

    /**
     * Creates new form DeanForm
     */
    public FacultyForm() {
        initComponents();
        adddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegisterFacultyBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Facultyname = new javax.swing.JTextField();
        UpdateFacultyBTN = new javax.swing.JButton();
        deleteFacultyBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Facultyd = new javax.swing.JTextField();
        SearchFacultyBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Faculty Registration Form");

        RegisterFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RegisterFacultyBTN.setText("Register");
        RegisterFacultyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterFacultyBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel2.setText("Full Names :");

        Facultyname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Facultyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultynameActionPerformed(evt);
            }
        });

        UpdateFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UpdateFacultyBTN.setText("Update");
        UpdateFacultyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateFacultyBTNActionPerformed(evt);
            }
        });

        deleteFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteFacultyBTN.setText("Delete");

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel3.setText("Faculty ID :");

        Facultyd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Facultyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultydActionPerformed(evt);
            }
        });

        SearchFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SearchFacultyBTN.setText("Search");

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel4.setText("Dean:");

        jComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Facultyd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(SearchFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(278, 278, 278)
                            .addComponent(RegisterFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(UpdateFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(deleteFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(382, 382, 382)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel4)
                                        .addGap(31, 31, 31)
                                        .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Facultyname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Facultyname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Facultyd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddata(){
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            Deanservise deans=(Deanservise) reg.lookup("Deancall");
           List<Dean> thedean=deans.deandata();
           if(thedean!=null){
               for(Dean deandata:thedean){
                   jComboBox.addItem(deandata);  
               }
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    private void FacultynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultynameActionPerformed

    private void FacultydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultydActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultydActionPerformed

    private void RegisterFacultyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterFacultyBTNActionPerformed
      ///Validation
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            FacultyServise facultys=(FacultyServise) reg.lookup("facultycall");
            Faculty dm =new Faculty();
            dm.setFacname(Facultyname.getText());
            Dean adddataitem=(Dean) jComboBox.getSelectedItem();
            dm.setDean(adddataitem);
            
            Faculty thefaculty=facultys.Registerdn(dm);
            if(thefaculty!=null){
                JOptionPane.showMessageDialog(this, "Data Saved Successful");
            }else{
                 JOptionPane.showMessageDialog(this, "Data not Saved");
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_RegisterFacultyBTNActionPerformed

    private void UpdateFacultyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateFacultyBTNActionPerformed
        //validation
        
    }//GEN-LAST:event_UpdateFacultyBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Facultyd;
    private javax.swing.JTextField Facultyname;
    private javax.swing.JButton RegisterFacultyBTN;
    private javax.swing.JButton SearchFacultyBTN;
    private javax.swing.JButton UpdateFacultyBTN;
    private javax.swing.JButton deleteFacultyBTN;
    private javax.swing.JComboBox<Dean> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
