/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Course;
import Model.Dean;
import Model.Department;
import Model.Faculty;
import Model.Student;
import Service.Courseservice;
import Service.Deanservise;
import Service.FacultyServise;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javafx.scene.control.ComboBox;
import javax.swing.JOptionPane;
import Service.DepartmentService;
import Service.StudentService;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author M NJERIC
 */
public class StudentForm extends javax.swing.JFrame {
private DefaultListModel<Course> defcourselist=new DefaultListModel<>();
    /**
     * Creates new form DeanForm
     */
    public StudentForm() {
        initComponents();
        adddatadepartment();
        adddatacourse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegisterFacultyBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        UpdateFacultyBTN = new javax.swing.JButton();
        deleteFacultyBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Facultyd = new javax.swing.JTextField();
        SearchFacultyBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        departmentlist = new javax.swing.JComboBox<>();
        studentname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courselistdata = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Department  Registration Form");

        RegisterFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RegisterFacultyBTN.setText("Register");
        RegisterFacultyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterFacultyBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel2.setText("Student ID :");

        studentid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });

        UpdateFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UpdateFacultyBTN.setText("Update");

        deleteFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteFacultyBTN.setText("Delete");

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel3.setText("Faculty ID :");

        Facultyd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Facultyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultydActionPerformed(evt);
            }
        });

        SearchFacultyBTN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SearchFacultyBTN.setText("Search");

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel4.setText("Course Name :");

        departmentlist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        studentname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel5.setText("Student Name :");

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel6.setText("DepartmentName :");

        courselistdata.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(courselistdata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Facultyd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(SearchFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(departmentlist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(431, 431, 431)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(298, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegisterFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(UpdateFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deleteFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(departmentlist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Facultyd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchFacultyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddatadepartment(){
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
           DepartmentService facs=(DepartmentService) reg.lookup("Departmentcall");
           List<Department> thedep=facs.deandata();
           if(thedep!=null){
               for(Department depts:thedep){
                   departmentlist.addItem(depts);  
               }
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    private void adddatacourse(){
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            Courseservice facs=(Courseservice) reg.lookup("Coursecall");
           List<Course> thecour=facs.deandata();
           if(thecour!=null){
               for(Course depts:thecour){
                  defcourselist.addElement(depts);
               }
               courselistdata.setModel(defcourselist);
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidActionPerformed

    private void FacultydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultydActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultydActionPerformed

    private void RegisterFacultyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterFacultyBTNActionPerformed
      ///Validation
        try {
            Registry reg=LocateRegistry.getRegistry("127.0.0.1", 7000);
            StudentService deptservice=(StudentService) reg.lookup("Studentcall");
            Student dm =new Student();
            dm.setStudentId(studentid.getText());
            dm.setNames(studentname.getText());
            Department adddataitem= (Department) departmentlist.getSelectedItem();
            dm.setDepartment(adddataitem);
            Set<Course> courseset=new  HashSet<>();
            List<Course> courselist=  courselistdata.getSelectedValuesList();
            for(Course thecourse:courselist){
                courseset.add(thecourse);
            }
            dm.setDepartment(adddataitem);
            dm.setCourses(courseset);
            Student thedep=deptservice.Registerdn(dm);
            if(thedep!=null){
                JOptionPane.showMessageDialog(this, "Data Saved Successful");
            }else{
                 JOptionPane.showMessageDialog(this, "Data not Saved");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_RegisterFacultyBTNActionPerformed

    private void studentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Facultyd;
    private javax.swing.JButton RegisterFacultyBTN;
    private javax.swing.JButton SearchFacultyBTN;
    private javax.swing.JButton UpdateFacultyBTN;
    private javax.swing.JList<Course> courselistdata;
    private javax.swing.JButton deleteFacultyBTN;
    private javax.swing.JComboBox<Department> departmentlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField studentname;
    // End of variables declaration//GEN-END:variables
}
